version: '2.1'

volumes:
  sense-data:
  dashboard-data:

services: 
  gpsd:
    privileged: true
    build: "./gpsd"
    devices: 
      - "/dev/ttyACM0:/dev/ttyACM0"
    environment:
      - "DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket"
    ports:
      - "2947"
    labels:
      io.resin.features.dbus: '1'
      io.balena.features.kernel-modules: '1'
  co2:
    privileged: true
    build: "./co2"
    network_mode: host  
    depends_on:
      - gpsd
    expose:
      - "2947"
      - "7575"
    labels:
      io.resin.features.dbus: '1'
      io.balena.features.kernel-modules: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1' 
