name: Tests for software/gpsd

on:
  push:
    branches: [ $default-branch ]
    paths: [ software/gpsd/** ]
  pull_request:
    branches: [ $default-branch ]
    paths: [ software/gpsd/** ]
  workflow_dispatch:
    branches: [ $default-branch ]
    paths: [ software/gpsd/** ]

jobs:
  build:
    defaults:
      run:
        working-directory: software/gpsd

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('software/gpsd/poetry.lock') }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies
      run: |
        poetry config virtualenvs.create false
        poetry install --no-root

    - name: Run checks
      run: ./check.sh